# docker image for storing automation codes
FROM fedora:21

MAINTAINER ybian <ybian@redhat.com>

# Do we need git? I think git is not necessary in this container, so rm install git step.
# Install basic packages include git vim
# RUN yum update -y
# RUN yum install git -y

# config git user.email and user.name
# RUN git config --global user.email 'ybian@redhat.com'
# RUN git config --global user.name 'ybian'

# set dir
WORKDIR /data/
